/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.uniza.fri.inf.todoList.app;

import sk.uniza.fri.inf.todoList.model.TodoList;
import sk.uniza.fri.inf.todoList.model.entity.TodoCategory;
import sk.uniza.fri.inf.todoList.model.entity.TodoItem;

import java.util.function.Function;

/**
 * @author Unlink
 */
public class ItemsList extends javax.swing.JPanel {

    private final TodoList todoList;
    private final TodoCategory category;
    private final Function<TodoItem, Boolean> onEdit;

    /**
     * Creates new form ItemsList
     */
    public ItemsList(TodoList todoList, TodoCategory category, Function<TodoItem, Boolean> onEdit) {
        initComponents();
        this.todoList = todoList;
        this.category = category;
        this.onEdit = onEdit;
        bindItems();
    }

    private void bindItems() {
        jPanelContent.removeAll();
        todoList.getItemsFor(category).sorted((o1, o2) -> {
            if (o1.isDone() && !o2.isDone()) {
                return 1;
            } else if (!o1.isDone() && o2.isDone()) {
                return -1;
            } else if (o1.getCreated() < o2.getCreated()) {
                return -1;
            } else if (o2.getCreated() < o1.getCreated()) {
                return 1;
            } else {
                return 0;
            }
        }).forEach((TodoItem t) -> {
            jPanelContent.add(new ItemView(t, todoList, (x) -> {
                bindItems();
                return true;
            }, onEdit, (y) -> {
                bindItems();
                return true;
            }));
        });
        invalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelContent = new javax.swing.JPanel();

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContent.setLayout(new javax.swing.BoxLayout(jPanelContent, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(jPanelContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    } // </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    void refresh() {
        bindItems();
    }

}
